# syntax = docker/dockerfile:1.2
FROM clojure:openjdk-17 AS build

WORKDIR /app
COPY . /app

RUN clj -Sforce -T:build all

########################################################################
FROM azul/zulu-openjdk-alpine:17

# Install telnet to access REPL on production
RUN apk --no-cache --update add busybox-extras

COPY --from=build /app/target/app-standalone.jar /app-standalone.jar

ENV PORT=3000
EXPOSE 3000

ENTRYPOINT exec java $JAVA_OPTS -jar /app-standalone.jar
